<!DOCTYPE html><html>
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>360云盘 - 我的云盘</title>
<script>var G_start_time = new Date;</script>
<!--[if (lt IE 8.0)]><link type="text/css" rel="stylesheet" href="http://c27.yunpan.360.cn/resource/css/my.src.css?v=144b7262.css" /><![endif]-->
<!--[if (!IE)|(gte IE 8.0)]><!-->
<link type="text/css" rel="stylesheet" href="http://c27.yunpan.360.cn/resource/css/my.src_datauri.css?v=f52df799.css" />
<!--<![endif]-->
<script type="text/javascript" src="http://c27.yunpan.360.cn/resource/js/components/1141.js?v=447542b3.js"></script>
</head>


<body>
   <img src='<?php echo $this->basePath();?>/admin/setting/qrcode' />
</body>
</html>
