<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Lsh Personal Blog'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap-responsive.min.css')
                        ?>
       <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)) ?>
       <style>
          body{
          	padding-top:45px;
         }
       </style>
    </head>
    <body>
        
     <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Lsh Personal Blog</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <a href="#" class="navbar-link">Username</a>
            </p>
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
    
    
        <div class="container-fluid">
			  <div class="row-fluid">
			    <div class="span9">
			       <?php echo $this->content; ?>
			    </div>
			    <div class="span3">
			       <div class="well sidebar-nav">
		            <ul class="nav nav-list">
		              <li class="nav-header">Recent Posts</li>
		              <li class="active"><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li class="nav-header">Recnet Comments</li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li class="nav-header">Categroy</li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li class="nav-header">Others</li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		              <li><a href="#">Link</a></li>
		            </ul>
		          </div><!--/.well -->
			    </div>
			  </div>
			  
			 <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y') ?> by Lsh710. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
		</div>
		<!-- Scripts -->
		<script type="text/javascript" src="<?php echo $this->basePath();?>/js/jquery.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
